sudo: required
language: java
notifications:
  email:
  - vertx3-ci@googlegroups.com
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.m2/repository
before_install:
- cp .travis.maven.settings.xml $HOME/.m2/settings.xml
install:
- mvn -version -B
script:
- mvn verify -B
