sudo: required
language: java
notifications:
  email:
  - vertx3-ci@googlegroups.com
jdk:
- oraclejdk8
before_install:
- cp .travis.maven.settings.xml $HOME/.m2/settings.xml
install: true
script:
- travis_wait 30 mvn -q -Dmaven.test.redirectTestOutputToFile verify -B
