sudo: required
language: java
notifications:
  email:
  - secure: "u6+7M1q/NDvw4WF287KtaK+F9tiVkI5WDXMdM6ttGz9kfKB50gwQRtWz4XwUxolFzc6Gs/tB6XV6K5De0LskIGPNxDt59ucIWpIjCCA9Qdpqdx6bqQ8VqbCOfq+r0vi+zhp6LkUi+o9s0Ni9HDmEUCEHDWF4NSQlvanKwQRzcCpfi4NuNKGoKtvlarOx5omj6S90hRZZdefvbkxCGVe4Y6Ahubv7FiQ/Ji81DkP1cBl45LMYTcPnMu/UtxntKNDmJM0h3hh+uHY6W6Z4sAKdkm1PcVou79smTBBMtamojLWGDzT3rCmyS8Aoy4UxVunQqkVkCGTYALtZI4LWD8A5514iadTC2ULI5TsYuD0N9fIwHvGqa70+QtnDKNWFCZFkxPO8oVtlWsJJDIHJkj876+ULhKDGPSD+fOsV0aHdzxtZ2uK4qtMQmjhQRYdRqxuAZDSYJ46g4olcNn9WPN3loLNVuPVumEihpjxaP9VBKNhjR773d65IwMjm2jCWXCmIXoymxSK2T7GS6VofyeBaz8YR6DGkQA/MQe52BCabyve7eioTkJl4n+qb/yUsVY2q9dl5DsAYsC4l/WJ8SzmnffLqj93gRwpzIyuJtiKUef9HHzUASh+MZYHRHlIV0LzLpLSErMLwehxsYpuKzjdvb7qqjLoIgIc3bGBXTsZEYz4="
jdk:
- oraclejdk8
branches:
  only:
  - master
  - initial-work
env:
  global:
  - secure: h/+qh4ettSXklrOCVp2oAU4ifiNEFZ7dyZwwJd8Tw+9+uD/osgUmHBFH8/q+EHzhYg2umSvrgkuxmj4ygJBPiBmWXk1/Tsr1HZqz6LJqg/g9csj1RQjgn+FDkFGJg7OD6ldiW4yuZwPcrjn8PkqxgrTmlf54rFJtGrXOfHxLgdh/IinBhTor2pldLT+QRPki5vQH5jk0HQIv2XC1N7R/5BjX54A/QghoMxIYYL4aRuHt2IlaRsmp8c49zo+6Z6BagP/MpxTEcm6gf+Cr9ZxMOT7qErHzXTQV7LE6JA0YeYuZpiDrlX23IItLQG55U4l+UAGxq0c2PGR05BsIRPsoxKQvprI4fW16kIemMv1ipM3ZbFH0+9kvn6rjF4YpUD+ZCVTEP1orYIy0WsZiAVOWIxRFvpurAP8ajWv5BFeSy4MzchieDZdV6yL9pgLVf/xDaNq86VovRJiRB1NCRk+UMyQsg+u+jINrfCR7lu6w1Kp0Jwit2hSaJL5tnIx95z/tZw8wWC1o73Jy6aTsfPBbVW1/f6yJZe75zEyQxzCfaDIJCm9DkD1uw4NBavxq57emNYxL+XX+voUAgNA9ePmivrHAiXQXaBbTkIOcoQkWSSjmgMeg30FC4/BIl5WmS+uHIouo0Nf0OUa3TX0BLscL2bx6yGKMS4e2hc3G788nLv8=
  - secure: VWgQgma2q8NClzbKA/jbV8AG0++fvy15P/qbQcN9kW+T7AklNyWOu6OhsseOOgLGR43P0/uVOizwi9yYJgHO4rm7Q7dvPrrycoZjyHDq7HtRUFfu66GlfWfoKrLCjZ6AbGO8bWKi+K+nigil5Cnqno4VGXfjLUjuwL4OIV8qGjTUyrdvbSY86h4bpYYhp9YMbKLdpW8yaaIFRFmAUnr7RP7R7vs6kZm1Eslgit1oSXdchrHNRfaqXvSL+GD1h1B+Q7Ebs7VbcY1ZLw0rqZ+FHnXbdNbb7H2alNH/NwqQGGY3B1AiqCQ0dfoAhFsPTfiSpG8r3RTsKH4sOGmIk+yWKxxCm+tdpJKeaPBo2S+RQZD0txS+1Mb1lNO9rObaW08KDIL5k6SFL8gZoiqkQqnL7OE1ylKP+ceNVocnmlfuFI+GqhzwOwg0YyMihnkn7vkLIrqFMNfgFrct1ENfgWRouRnZUg31YKKjrYZfG9yYpq9KmKFHI+d3v6Hfp1J5MLBCPPOs5/JoXAUwAVgzRq9fKFLd2MmGtjhYguMRWzWaveswRt+xI0lmxabxQpkMvd7zX7sLBpoX4IP7/PTCMZp7I1fhhel9WjLqFVGzleKx2VdBfrv/0NuGyu6aJvO36gd0eATBXzC/bAai6097UWg3NiufzLNkotdWttEn6B5qP0A=
before_install:
- cp .travis.maven.settings.xml $HOME/.m2/settings.xml
install: true
script:
- set -e
- mvn -DtestLogLevel=OFF clean verify -B
- bash .travis.deploy.artifacts.sh
